[package]
name = "zfp-sys"
version = "0.1.0"
authors = ["jvo203 <chris.zapart@nao.ac.jp>"]
edition = "2018"
description = "Raw Rust bindings to ZFP"
license-file = "LICENSE"

[build-dependencies]
bindgen = "*"
cmake = "*"

[dependencies]
